# From: https://docs.k3s.io/networking/multus-ipams#deploy-with-an-ipam-plugin
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: multus
  namespace: kube-system
spec:
  repo: https://rke2-charts.rancher.io
  chart: rke2-multus
  version: v4.2.106 # Note that a specific version is used. During the last test, later versions do not work properly. Maybe now the issue is fixed
  targetNamespace: kube-system
  valuesContent: |-
    config:      
      fullnameOverride: multus
      cni_conf:
        confDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
        binDir: /var/lib/rancher/k3s/data/cni/
        kubeconfig: /var/lib/rancher/k3s/agent/etc/cni/net.d/multus.d/multus.kubeconfig
    manifests:
      dhcpDaemonSet: true
