- name: Check if K3s is already installed
  command: k3s --version
  register: k3s_version_check
  failed_when: false
  changed_when: false
  tags: test

- name: Message if K3s is already installed
  debug:
    msg: "✅ K3s is installed"
  when: k3s_version_check.rc == 0
  tags: test

- name: Message if K3s is NOT installed
  debug:
    msg: "K3s is NOT installed. Starting installation..."
  when: k3s_version_check.rc != 0
  tags: test

- name: Install K3s if not installed
  block:

    - name: Check if curl is installed
      command: which curl
      register: curl_check
      failed_when: false
      changed_when: false

    - name: Install curl if not present
      apt:
        name: curl
        state: present
        update_cache: yes
      become: true
      when: curl_check.rc != 0

    - name: Install K3s if not installed
      shell: curl -sfL https://get.k3s.io | K3S_NODE_NAME={{ k3s_node_name }} K3S_KUBECONFIG_MODE={{ k3s_kubeconfig_mode }} sh -
      become: true
      tags: test

    - name: Add KUBECONFIG to profile
      lineinfile:
        path: ~/.profile
        line: 'export KUBECONFIG="{{ kubeconfig }}"'
        state: present
        create: yes
      tags: test

    - name: Get KUBECONFIG value
      shell: bash -lc 'echo $KUBECONFIG'
      register: kubeconfig_value
      tags: test

    - name: Show KUBECONFIG value
      debug:
        msg: "KUBECONFIG environment variable = {{ kubeconfig_value.stdout }}"
      tags: test

  tags: test

# - name: Uninstall K3s
#   shell: /usr/local/bin/k3s-uninstall.sh
#   tags: uninstall
